[workspace]
resolver = "2"

members = [
	"calc",
	"datetime",
	"dev",
	"display",
	"file",
	"fs",
	"m4",
	"m4/test-manager",
	"gettext-rs",
	"misc",
	"pathnames",
	"plib",
	"process",
	"sccs",
	"screen",
	"sys",
	"text",
	"tree",
	"users",
	"xform",
	"i18n"
]

[workspace.dependencies]
atty = "0.2"
clap = { version = "4", default-features = false, features = ["std", "derive", "help", "usage", "error-context", "cargo"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
libc = "0.2"
regex = "1.10"
gettext-rs = { path = "./gettext-rs" }
