[package]
name = "posixutils-dev"
version = "0.1.3"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
object = "0.33"

[[bin]]
name = "nm"
path = "src/nm.rs"

