[package]
name = "posixutils-display"
version = "0.1.3"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }

[[bin]]
name = "echo"
path = "src/echo.rs"

[[bin]]
name = "printf"
path = "src/printf.rs"

