[package]
name = "posixutils-process"
version = "0.1.3"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
libc = "0.2"
errno = "0.3"
regex = "1.10"

[[bin]]
name = "env"
path = "src/env.rs"

[[bin]]
name = "kill"
path = "src/kill.rs"

[[bin]]
name = "nice"
path = "src/nice.rs"

[[bin]]
name = "renice"
path = "src/renice.rs"

[[bin]]
name = "xargs"
path = "src/xargs.rs"

