[package]
name = "posixutils-text"
version = "0.1.3"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
topological-sort = "0.2"

[[bin]]
name = "asa"
path = "src/asa.rs"

[[bin]]
name = "comm"
path = "src/comm.rs"

[[bin]]
name = "expand"
path = "src/expand.rs"

[[bin]]
name = "fold"
path = "src/fold.rs"

[[bin]]
name = "head"
path = "src/head.rs"

[[bin]]
name = "paste"
path = "src/paste.rs"

[[bin]]
name = "tsort"
path = "src/tsort.rs"

[[bin]]
name = "wc"
path = "src/wc.rs"

