[package]
name = "posixutils-xform"
version = "0.1.3"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap = { version = "4", features = ["derive"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
uuencode = "0.1"
base64 = "0.21"

[[bin]]
name = "cksum"
path = "src/cksum.rs"

[[bin]]
name = "uncompress"
path = "src/uncompress.rs"

[[bin]]
name = "uudecode"
path = "src/uudecode.rs"

[[bin]]
name = "uuencode"
path = "src/uuencode.rs"

